
@echo off

REM !!! Generated by the fmp-cli 1.62.0.  DO NOT EDIT!

md SideMenu\Assets\3rd\fmp-xtc-sidemenu

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-sidemenu-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\SideMenu\Assets\3rd\fmp-xtc-sidemenu\
